FirstApp/FirstApp/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FirstApp.Models;
using FirstApp.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FirstApp.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventRepository _eventRepository;
        private readonly IStageRepository _stageRepository;

        public EventController(IEventRepository iEventRepository, IStageRepository iStageRepository)
        {
            _eventRepository = iEventRepository;
            _stageRepository = iStageRepository;
        }

        public ViewResult List()
        {
            EventsListViewModel eventsListViewModel = new EventsListViewModel
            {
                Events = _eventRepository.Events.OrderBy(e => e.MountainHeight).ToList(),
            };

            return View(eventsListViewModel);
        }

        public IActionResult Details(int id)
        {
            var eevent = _eventRepository.GetEventById(id);
            if (eevent == null)
            return NotFound();
            return View(eevent);
        }

        public IActionResult EventManagement()
        {
            var events = _eventRepository.Events.OrderBy(o => o.MountainHeight);
            foreach (var ev in events)
            {
                ev.Stage = new Stage(_stageRepository.GetStageById(ev.StageId));
            }
            return View(events);
        }

        public IActionResult AddEvent()
        {
            var addEventViewModel = new AddEventViewModel();
            foreach (var stage in _stageRepository.Stages)
            {
                addEventViewModel.StagesList.Add(stage);
            }
            return View(addEventViewModel);
        }

        [HttpPost]
        public IActionResult AddEvent(AddEventViewModel addEventViewModel)
        {
            if (!ModelState.IsValid)
            {
                foreach (var stage in _stageRepository.Stages)
                {
                    addEventViewModel.StagesList.Add(stage);
                }
                return View(addEventViewModel);
            }
            Event ev = new Event
            {
                EventName = addEventViewModel.EventName,
                MountainName = addEventViewModel.MountainName,
                MountainRange = addEventViewModel.MountainRange,
                ShortDescription = addEventViewModel.ShortDescription,
                LongDescription = addEventViewModel.LongDescription,
                DateOfCompletion = addEventViewModel.DateOfCompletion,
                PlannedDate =  addEventViewModel.PlannedDate,
                Location = addEventViewModel.Location,
                DistanceToTravel = addEventViewModel.DistanceToTravel,
                MountainHeight = addEventViewModel.MountainHeight,
                EstimatedHeightToClimb = addEventViewModel.EstimatedHeightToClimb,
                NumberOfPeopleInvolved = addEventViewModel.NumberOfPeopleInvolved,
                DistnceTraveledOnFootInMeters = addEventViewModel.DistnceTraveledOnFootInMeters,
                MountainsProminenceTravelled = addEventViewModel.MountainsProminenceTravelled,
                Status = addEventViewModel.Status,
                MapHtml = addEventViewModel.MapHtml,
                Image =  addEventViewModel.Image,
                StageId = addEventViewModel.StageId
            };

            if (ModelState.IsValid)
            {
                _eventRepository.AddEvent(ev);
                return RedirectToAction("EventManagement");
            }

            return View(addEventViewModel);
        }

        public IActionResult EditEvent(int id)
        {
            Event ev =  _eventRepository.GetEventById(id);
            AddEventViewModel editEvent = new AddEventViewModel(ev);
            editEvent.Stage = _stageRepository.GetStageById(editEvent.StageId);
            foreach (var stage in _stageRepository.Stages)
            {
                editEvent.StagesList.Add(stage);
            }
            if (ev == null) return RedirectToAction("EventManagement", _eventRepository.Events);

            return View(editEvent);
        }

        [HttpPost]
        public IActionResult EditEvent(AddEventViewModel addEventViewModel)
        {
            if (!ModelState.IsValid)
            {
                foreach (var stage in _stageRepository.Stages)
                {
                    addEventViewModel.StagesList.Add(stage);
                }
                return View(addEventViewModel);
            }

            if (ModelState.IsValid)
            {
                _eventRepository.EditEvent(addEventViewModel);
                return RedirectToAction("EventManagement");
            }

            return View(addEventViewModel);
        }

        public IActionResult DeleteEvent(int id)
        {
            Event ev = _eventRepository.GetEventById(id);
            ev.Stage = _stageRepository.GetStageById(ev.StageId);
            return View(ev);
        }

        [HttpPost]
        public IActionResult DeleteEvent(Event eve)
        {
            Event ev =  _eventRepository.GetEventById(eve.EventId);
            if (ev != null)
            {
                _eventRepository.RemoveEvent(ev);
            }

            return View("EventManagement", _eventRepository.Events);
        }
    }
}

FirstApp/FirstApp/Controllers/StageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FirstApp.Models;
using FirstApp.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FirstApp.Controllers
{
    public class StageController : Controller
    {
        private readonly IStageRepository _iStageRepository;
        private readonly IEventRepository _iEventRepository;

        public StageController(IStageRepository stageRepository, IEventRepository eventRepository)
        {
            _iStageRepository = stageRepository;
            _iEventRepository = eventRepository;
        }

        // GET: Stage
        public ActionResult StageSummary(int id)
        {
            var stage = _iStageRepository.GetStageById(id);
            if (stage == null) return NotFound();
            stage.Events = _iStageRepository.GetStageEventsById(id).ToList();
            
            return View(stage);
        }

        public IActionResult StageDetails(int id)
        {
            var stage = _iStageRepository.GetStageById(id);
            if (stage == null) return NotFound();
            return View(stage);
        }

        public IActionResult StagesManagement()
        {
            var stages = _iStageRepository.Stages.OrderBy(s => s.StageName).ToList();
            return View(stages);
        }

        public IActionResult AddStage()
        {
            return View(new Stage());
        }

        [HttpPost]
        public IActionResult AddStage(Stage stage)
        {
            if (!ModelState.IsValid) return View(stage);
            if (ModelState.IsValid)
            {
                _iStageRepository.AddStage(stage);
                return RedirectToAction("StagesManagement", _iStageRepository.Stages);
            }

            return View(stage);
        }

        public IActionResult EditStage(int id)
        {
            var stage = _iStageRepository.GetStageById(id);
            if (stage == null) return NotFound();
            return View(stage);
        }

        [HttpPost]
        public IActionResult EditStage(Stage stage)
        {
            if (!ModelState.IsValid) return View(stage);
            if (ModelState.IsValid)
            {
                _iStageRepository.EditStage(stage);
                return RedirectToAction("StagesManagement", _iStageRepository);
            }
            return View(stage);
        }

        [HttpPost]
        public IActionResult DeleteStage(int id)
        {
            var stage = _iStageRepository.GetStageById(id);
            if (stage == null) return NotFound();
            _iStageRepository.DeleteStage(stage);

            return RedirectToAction("StagesManagement");
        }
    }
}

FirstApp/FirstApp/Views/Shared/EventSummary.cshtml
@model Event

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <h3 class="pull-right">@Model.MountainHeight</h3>
        <h3>
            <a>@Model.EventName</a>
        </h3>
        <a asp-controller="Event" asp-action="Details" asp-route-id="@Model.EventId">@Model.MountainName</a>
        <p>@Model.ShortDescription</p>
    </div>
        
</div>

FirstApp/FirstApp/Views/Shared/_Layout.cshtml
@using FirstApp.Auth
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>

@inject SignInManager<ApplicationUser> SignInManager


<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE-edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Śmigaj w góry!</title>

    <link href="~/Images/2017124112017-09-063832922Mountains.jpg" rel="icon" />
    <!--css libs-->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet">
    <link href="~/lib/animate/animate.min.css" rel="stylesheet" />
    <link href="~/lib/ionicons/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />

    <link href="~/lib/css/style.css" rel="stylesheet" />
</head>

<body>
    <!--Header-->
<header id="header">
    <div class="container">

        <div class="logo float-left">
            <a asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/Images/2017124112017-09-063832922Mountains.jpg" alt="" class="img-fluid scrollto"> ŚMIGAJ W GÓRY!</a>
        </div>
        <!-- .main-nav -->
        <nav class="main-nav float-right d-none d-lg-block">
            <ul>
                @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {
                    <li class="drop-down">
                        <a href="">Admin</a>
                        <ul>
                            <li><a asp-controller="Admin" asp-action="UserManagement" class="navbar-brand">Zarządzaj użytkownikami</a></li>
                            <li><a asp-controller="Admin" asp-action="RoleManagement" class="navbar-brand">Zarządzaj rolami</a></li>
                            <li><a asp-controller="Event" asp-action="EventManagement" class="navbar-brand">Zarządzaj eventami</a></li>
                            <li><a asp-controller="Stage" asp-action="StagesManagement" class="navbar-brand">Zarządzaj etapami</a></li>
                        </ul>
                    </li>
                }
                <li><a asp-controller="Home" asp-action="Index" class="navbar-brand">Strona główna</a></li>
                <li><a asp-controller="Event" asp-action="List" class="navbar-brand">Lista szczytów</a></li>
                <li><a asp-controller="Feedback" asp-action="Index" class="navbar-brand">Podziel się opinią</a></li>
                @if (SignInManager.IsSignedIn(User))
                {
                    <li>
                        <form asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-brand">
                            <a href="javascript:document.getElementById('logoutForm').submit()">Wyloguj się</a>
                        </form>
                    </li>
                }
                else
                {
                    <li><a asp-controller="Account" asp-action="Login" class="navbar-brand">Zaloguj się</a></li>
                    <li><a asp-controller="Account" asp-action="Register" class="navbar-brand">Załóż konto</a></li>
                }
            </ul>
        </nav>

    </div>
</header>

    <!--Main section-->
    <main id="main">
        <div class="">
            @RenderBody()
        </div>
    </main>
    <!--Footer-->
    <footer id="footer" class="section-bg position-relative">
        <div class="footer-top">
            <div class="container">

                <div class="row">

                    <div class="col-lg-12">

                        <div class="row">

                            <div class="col-sm-12">
                                <div class="footer-links text-center copyright" style="">
                                    <p style="margin-bottom: 5px; font-weight: bold">Kontakt</p>
                                    <div class="social-links" style="margin-bottom: 5px;">
                                        <a href="#" class=""><i class="fab fa-facebook-square"></i></a>
                                        <a href="#" class=""><i class="fab fa-instagram center"></i></a>
                                        <a href="#" class=""><i class="fab fa-linkedin center"></i></a>
                                    </div>
                                        <strong>Email:</strong> filip.marek.lipinski@gmail.com<br>
                                </div>

                            </div>

                        </div>

                    </div>
                </div>

            </div>
        </div>

        <div class="container">
            <div class="copyright">
                © Copyright <strong>Rapid</strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!--
              All the links in the footer should remain intact.
              You can delete the links only if you purchased the pro version.
              Licensing information: https://bootstrapmade.com/license/
              Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Rapid
            -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
    </footer>

    <a href="#" class="back-to-top">
        <i class="fa fa-chevron-up"></i>
    </a>
    <!--js libraries-->
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/counterup/counterup.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/mobile-nav/mobile-nav.js"></script>
    <script src="~/lib/isotope/isotope.pkgd.min.js"></script>
    <script src="~/lib/lightbox/js/lightbox.min.js"></script>

    <script src="~/lib/js/main.js"></script>
</body>
</html>